### ISSUE TITLE
Combine repo with python and other languages?

### ISSUE THREAD

**Issue by JoshOrndorff** [rchain/rchain-api#12]
There has been discussion on discord and around the community about whether this repo should be shared with python similar apis in other languages like python.

Relevant python code:
https://github.com/proof-media/rchain-grpc
https://github.com/proof-media/rchain-notebook
https://github.com/rchain/rchain/tree/dev/node-client

Relevant Jira issue:
https://rchain.atlassian.net/browse/OPS-330

**Comment by dckc** [comment]
@cboscolo wrote on Oct7:
> I encourage folks to check out how the Ethereum project does it. (https://github.com/ethereum)   Like it or not, they are the benchmark for large public blockchain projects. We should mimic what they do well, and modify what they do not do well.  The Ethereum git org does host Ethereum clients, and they do it one repo per language.

phil and Kent gave it a thumbs-up

I find it persuasive too.

phil elaborated:
> one for each language and more specifically one for each project ( there can be multiple libraries or implementations in general projects in the same language), see web3.js and solc-js or pyethereum and web3.py for ethereum

**Comment by dckc** [comment]
MG argued against 3rd party projects under https://github.com/rchain/ .

It seems to me that the decision to put something under https://github.com/rchain/ is a decision to say it's official and not 3rd party.

**Comment by justinmeiners** [comment]
I would vote not having them in the same repo, as the distribution and structure for each will be different. For example, the javascript should eventually be published as an npm package, and the published package will reference with repo. Some other platform distributions might pull from the repo directly.  Arguably, nothing will be shared except the protobuf files that are used to generate some parts.  

@dckc isn't this official?

**Comment by JoshOrndorff** [comment]
I agree that we should have one repo per project. (Just thought maybe that wasn't how it worked around here since rchain/rchain is so big).  I'm going to close this. Feel free to re-open if this needs more discussion. But, the decision to have separate repos, makes the conversation about what to call this one more relevant.
