### ISSUE TITLE
Update api for required cost accounting parameters

### ISSUE THREAD

**Issue by JoshOrndorff** [rchain/rchain-api#14]
As on node 0.7, `phlo-price`, and `phol-limit` are required. The API should reflect that and require them as well.

**Comment by goral09** [comment]
https://github.com/rchain/rchain/pull/1555/files#diff-716fefb13120384ecb72c40ff4a9bca0R310

**Comment by dckc** [comment]
@crypto-coder writes:
> How to version the API against a moving RNode target?

I'd say: with issues such as this one and #6

And yes, any change in the gRPC layer is an observable change in the API for this package, so the version number should change. Breaking changes in the gRPC layer imply breaking changes in this package.

**Comment by JoshOrndorff** [comment]
Do we agree that our [https://semver.org/](semantic versioning) numbers will just match core?

**Comment by JoshOrndorff** [comment]
Our intention is to stay up to date with the node releases, and making a semi-formal agreement not to lag behind them by more than one week.
