### ISSUE TITLE
move to rchain-community github org?

### ISSUE THREAD

**Issue by dckc** [rchain/rchain-api#29]
Admin under https://github.com/rchain isn't going as smoothly as I'd hoped. e.g. #20, #27 .

A while back I was invited to join https://github.com/rchain-community ; I didn't jump in back then because I wasn't sure how much of the community it represented, but now that I see stuff like https://github.com/rchain-community/rholang-syntax-highlighting there, I'm more inclined to join in.

cc @tschoffelen

**Comment by tschoffelen** [comment]
Would be great to have this on @rchain-community!

Your invite to join the org should still be open, feel free to place it there, you should have the appropriate permissions to do so I think.

**Comment by dckc** [comment]
in the spirit of decentralization, I give you: https://github.com/rchain-community/rchain-api

Whether to move issue tracking is another question... it would help so I can make milestones and such... hmm...

**Comment by dckc** [comment]
The fork structure is a little odd. Most forks descend from Joshy's repo. I wish we had moved his repo to rchain-community. Maybe we still could / should?

[Moving issues between repositories][1] is supported now.

[1]: https://help.github.com/articles/transferring-an-issue-to-another-repository/

**Comment by tschoffelen** [comment]
@dckc Let me know if you need any support from me in moving stuff over, or renaming/archiving/deleting repos in the rchain-community org!

**Comment by JoshOrndorff** [comment]
Yeah, I guess github isn't smart enough to realize that this repo has common history with mine.

How about this plan.
1. Delete the existing rchain-community/rchain-api
2. Move JoshOrndorff/rchain-api to rchain-community/rchain-api
3. Form rchain-community/rchain-api back to JoshOrndorff/rchain-api

**Comment by dckc** [comment]
More or less, yes; but take care not to lose issues.

**Comment by tschoffelen** [comment]
I would first just rename the version on rchain-community. I think both of you should have permissions to do so.

Give me a ping when the migration is done, then I can remove the old one.

**Comment by dckc** [comment]
some progress today, but see https://github.com/rchain-community/RChain-API/issues/31 about admin access

**Comment by dckc** [comment]
@JoshOrndorff please close the issues you raised in this repo. I think that would wrap up the migration.

**Comment by JoshOrndorff** [comment]
done!
