### ISSUE TITLE
npm/pypi/etc package name: rchain? rchain-api?

### ISSUE THREAD

**Issue by JoshOrndorff** [rchain/rchain-api#4]
_From @dckc on October 3, 2018 21:43_

In #19, @crypto-coder suggests `npm install --save rchain`. @JoshOrndorff says he likes it.

Hmm... it seems like a land-grab, to me; are we really developing *the* rchain module?

Not that `rchain-api` was any less of a land-grab. Hmm...

_Copied from original issue: JoshOrndorff/RChain-API#22_

**Comment by JoshOrndorff** [comment]
I think we're developing _the_ rchain module for javascript. Taking that name doesn't preclude development of `rchain.py` or `rchain.java`. We could even pronounce the project "RChain JS".

The one situation I can imagine making me regret the land-grab is if someone wants to develop the actual node in javascript. But I think js would be pretty far down the list preferred languages for that.

**Comment by JoshOrndorff** [comment]
Although I'm certainly open to suggestions @dckc if you have something you like more.

**Comment by JoshOrndorff** [comment]
_From @dckc on October 3, 2018 22:22_

Maybe `rchain-client`? Or `rchain-sidecar`?

I would think *the* rchain package for javascript would re-implement the rholang interpreter / compiler and the rest of the scala code.

I prefer less meaningful names that accrue their own reputation later rather than grabbing up front. (historical example: HTML Wilbur that later became HTML 3.2). Hmm... `rchain-dapper` for building dapps? Maybe `rchain-tools`? But that smells like a [util package](http://www.adam-bien.com/roller/abien/entry/util_packages_are_evil).

rchain-gang
rchain-web
rchain-connect

using some words from a bip39 generator:
rchain-leaf
rchain-bubble
rchain-blossom
rchain-panther

**Comment by JoshOrndorff** [comment]
panthR

**Comment by JoshOrndorff** [comment]
Now that we're moved into a new repo I propose we go with `rchain-api` all lowercase. Any opposition reopen.

**Comment by dckc** [comment]
Good. That's what's been in package.json since July 28 :)

https://github.com/rchain/rchain-api/blame/master/package.json#L2

**Comment by dckc** [comment]
@JoshOrndorff writes Oct 13 in #12 :
> But, the decision to have separate repos, makes the conversation about what to call this one more relevant.

Sounds like this issue should be re-opened.

Please either re-open it or invite me as collaborator so I can do it.

cc @crypto-coder

**Comment by JoshOrndorff** [comment]
Looks like I don't have privs to invite. _reaches for his revokable forwarder factory..._

**Comment by dckc** [comment]
**RChainJS** is Ok by me. (proposed by @crypto-coder)

Please let's use a separate comment on each name that anybody is advocating and use :+1: and :-1: reactions.

_My preference is still rchain-api ; I gave it a thumbs-up above._

**Comment by crypto-coder** [comment]
"rchain-api" is the final name we chose on the call tonight.   Issue Resolved.


TypeScript syntax would look like this -- 
import { RNodeClient, TupleSpaceClient, Block, Registry} from 'rchain-api';

web3.eth is how Ethereum does things now
web3.rchain is how RChain could do things in the future
